<?php
/**
 * @copyright Copyright (c) Michael Hüneburg
 * @link https://github.com/michaelhue/craft-breakpoint
 * @license https://craftcms.github.io/license/
 */

namespace michaelhue\breakpoint\web\assets\livepreview;

use craft\web\AssetBundle;
use craft\web\View;
use michaelhue\breakpoint\Plugin;

/**
 * Asset bundle for the plugin's Live Preview extensions.
 *
 * @author Michael Hüneburg
 * @since 1.0.0
 */
class LivePreviewAsset extends AssetBundle
{
	/**
	 * @inheritdoc
	 */
	public function init()
	{
		parent::init();

		$this->depends = [
			'craft\web\assets\cp\CpAsset',
		];

		$this->sourcePath = __DIR__ . '/dist';

		$this->css = ['LivePreview.min.css'];

		$this->js = ['LivePreview.min.js'];
	}

	/**
	 * @inheritdoc
	 */
	public function registerAssetFiles($view)
	{
		parent::registerAssetFiles($view);

		if ($view instanceof View) {
			$this->registerInitJs($view);
			$this->registerTranslations($view);
		}
	}

	/**
	 * Add JS code for initializing the asset.
	 */
	protected function registerInitJs(View $view)
	{
		$settings = Plugin::getInstance()->getSettings();
		$json = $settings->toJson();

		$lines = [
			'/* Generated by michaelhue/craft-breakpoint */',
			';(function initBreakpointLivePreview(ctx) {',
			'  if (!("BreakpointLivePreview" in ctx)) return;',
			'  new ctx.BreakpointLivePreview((' . $json . '));',
			'}(window));',
		];

		$view->registerJs(implode(PHP_EOL, $lines));
	}

	/**
	 * Register i18n messages for front-end translations.
	 */
	protected function registerTranslations(View $view)
	{
		$view->registerTranslations('breakpoint', [
			'Fit',
			'Height',
			'Presets',
			'Responsive',
			'Rotate',
			'Toggle screen sizes',
			'Width',
			'Zoom',
		]);
	}
}
